version: 2

jobs:
  build-job:
    working_directory: ~/styled-recycler-view

    docker:
      - image: circleci/android:api-27-alpha

    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xms256m -Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'

    steps:
      - checkout

      - restore_cache:
          key: project-{{ checksum "build.gradle" }}-{{ checksum "dependencies.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "dependencies.gradle" }}

      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies --stacktrace

      - save_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "dependencies.gradle" }}
          paths:
            - ~/android

      - run:
          name: Run unit test
          command: |
            ./gradlew testDebugUnitTest -PtestProguard=true --stacktrace

      - store_test_results:
          path: styled-recycler-view/build/test-results
      - store_test_results:
          path: styled-switch-view/build/test-results

      - save_cache:
          key: project-{{ checksum "build.gradle" }}-{{ checksum "dependencies.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - "~/.gradle/"
            - "~/.m2"

  deploy-job:
    working_directory: ~/styled-recycler-view

    docker:
      - image: circleci/android:api-27-alpha

    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xms256m -Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'

    steps:
      - checkout

      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies --stacktrace

      - run:
          name: Run unit test
          command: |
            ./gradlew testReleaseUnitTest --stacktrace

      - run:
          name: Build artifact
          command: |
            ./gradlew build --stacktrace

      - run:
          name: Publish to Github
          command: |
            ./gradlew styled-recycler-view:githubRelease --stacktrace 2> /dev/null
            ./gradlew styled-switch-view:githubRelease --stacktrace 2> /dev/null

      - run:
          name: Publish to JCenter
          command: |
            ./gradlew styled-recycler-view:bintrayUpload --stacktrace 2> /dev/null
            ./gradlew styled-switch-view:bintrayUpload --stacktrace 2> /dev/null

      - store_artifacts:
          path: styled-recycler-view/build/outputs/aar/
          destination: aar
      - store_artifacts:
          path: styled-switch-view/build/outputs/aar/
          destination: aar

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job:
          filters:
            branches:
              ignore: master
      - deploy-job:
          filters:
            branches:
              only: master
